# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 07:55
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryId', models.IntegerField()),
                ('typeSettlementId', models.IntegerField()),
                ('settlementId', models.IntegerField()),
                ('districtId', models.IntegerField()),
                ('streetId', models.IntegerField()),
                ('houseNumber', models.IntegerField()),
                ('apartmentNumber', models.IntegerField(null=True)),
                ('imagesId', models.IntegerField(null=True)),
                ('zipId', models.IntegerField(null=True)),
                ('detailsInfoJson', django.contrib.postgres.fields.jsonb.JSONField()),
                ('publishedDate', models.DateTimeField(default=datetime.datetime(2016, 12, 5, 7, 55, 5, 246684, tzinfo=utc))),
                ('updatedDate', models.DateTimeField(default=datetime.datetime(2016, 12, 5, 7, 55, 5, 246783, tzinfo=utc))),
            ],
        ),
    ]
